import {esc as e} from './utils.js';
export function distanceKm(a,b){const rad=x=>x*Math.PI/180;const dlat=rad(b.lat-a.lat),dlng=rad(b.lng-a.lng);const h=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlng/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
export function locationMarkup(t){return `<section class="location-finder" aria-labelledby="location-heading"><div><span class="eyebrow">${e(t.etiqueta)}</span><h2 id="location-heading">${e(t.titulo)}</h2><p>${e(t.descricao)}</p></div><form id="location-form"><label class="field" for="location-query">${e(t.label)}</label><div class="location-input"><input id="location-query" required minlength="2" maxlength="160" placeholder="${e(t.placeholder)}" autocomplete="off"><button class="btn" type="submit">${e(t.procurar)}</button><button class="btn outline" type="button" id="location-clear" hidden>${e(t.limpar)}</button></div></form><p class="location-note">${e(t.privacidade)} <a href="https://photon.komoot.io" target="_blank" rel="noopener">Photon</a> / <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>.</p><p id="location-status" role="status"></p><div id="location-choices"></div><div id="nearest-result" aria-live="polite"></div></section>`;}
export function initLocation(config,t,onSelect){const form=document.querySelector('#location-form'),input=document.querySelector('#location-query'),status=document.querySelector('#location-status'),choices=document.querySelector('#location-choices'),clear=document.querySelector('#location-clear'),submit=form.querySelector('[type=submit]');let controller,version=0,last=0;const cache=new Map();
 const reset=()=>{version++;controller?.abort();submit.disabled=false;choices.replaceChildren();status.textContent='';onSelect(null);};
 input.addEventListener('input',()=>{reset();clear.hidden=!input.value;});
 clear.onclick=()=>{input.value='';reset();clear.hidden=true;input.focus();};
 form.onsubmit=async event=>{event.preventDefault();const query=input.value.trim();if(query.length<2)return;const id=++version;controller?.abort();controller=new AbortController();const signal=controller.signal;submit.disabled=true;clear.hidden=false;choices.replaceChildren();onSelect(null);status.textContent=t.aProcurar;let timeout;
 try{let places=cache.get(query.toLocaleLowerCase('pt-PT'));if(!places){const wait=Math.max(0,1200-(Date.now()-last));if(wait)await new Promise(resolve=>setTimeout(resolve,wait));if(id!==version)return;last=Date.now();const url=new URL(config.endpoint);url.search=new URLSearchParams({q:query,limit:'5',countrycode:'PT',lat:'41.18',lon:'-8.2'});timeout=setTimeout(()=>controller.abort(),12000);const response=await fetch(url,{signal});if(!response.ok)throw Error();const data=await response.json();places=(data.features||[]).filter(x=>x.geometry?.type==='Point'&&x.geometry.coordinates.every(Number.isFinite)&&Math.abs(x.geometry.coordinates[1])<=90&&Math.abs(x.geometry.coordinates[0])<=180&&(!x.properties.countrycode||x.properties.countrycode.toUpperCase()==='PT')).map(x=>{const p=x.properties;return {lat:x.geometry.coordinates[1],lng:x.geometry.coordinates[0],label:[...new Set([p.name,p.street,p.housenumber,p.postcode,p.city,p.county,p.state].filter(Boolean))].join(', ')};});places=places.filter((p,i,all)=>all.findIndex(x=>x.label===p.label)===i);cache.set(query.toLocaleLowerCase('pt-PT'),places);}if(id!==version)return;status.textContent=places.length?t.escolher:t.semResultados;
 choices.innerHTML=places.map((p,i)=>`<button class="location-choice" type="button" data-place="${i}">${e(p.label)}</button>`).join('');choices.querySelectorAll('button').forEach(b=>b.onclick=()=>{const place=places[Number(b.dataset.place)];choices.replaceChildren();status.textContent=`${t.selecionada} ${place.label}`;onSelect(place);});
 }catch{if(id===version)status.textContent=t.erro;}finally{clearTimeout(timeout);if(id===version)submit.disabled=false;}
 };
}
