import {readFlyer,saveFlyer,resetFlyer} from './flyer-store.js';
import {esc as e} from './utils.js';
import {openViewer} from './viewer.js?v=20261001-2';
const root=document.querySelector('#panel');
try{
const cfg=await (await fetch('/data/config.json',{cache:'no-store'})).json(),t=cfg.painel;let saved=await readFlyer(),candidate=saved;
root.innerHTML=`<header class="panel-heading"><a href="/"><img src="/${e(cfg.marca.logo)}" alt="${e(cfg.marca.nome)}"></a><a class="btn outline" href="/">${e(t.voltar)}</a></header><span class="eyebrow">${e(t.etiqueta)}</span><h1>${e(t.titulo)}</h1><p class="panel-intro">${e(t.descricao)}</p><div class="panel-notice">${e(t.aviso)}</div><form class="panel-form"><label class="field">${e(t.pdf)}<input type="file" id="pdf" accept="application/pdf,.pdf"><small>${e(t.limite)}</small></label><p id="file-info"></p><label class="field">${e(t.nome)}<input id="title" required maxlength="120"></label><div class="panel-dates"><label class="field">${e(t.inicio)}<input id="start" type="date" required></label><label class="field">${e(t.fim)}<input id="end" type="date" required></label></div><div class="panel-actions"><button class="btn" type="submit">${e(t.guardar)}</button><button class="btn outline" type="button" id="preview">${e(t.preview)}</button><button class="btn outline" type="button" id="reset">${e(t.repor)}</button></div><p role="status" id="panel-status" aria-live="polite"></p></form>`;
root.removeAttribute('aria-busy');const field=id=>document.getElementById(id),status=text=>field('panel-status').textContent=text;
function fill(){field('title').value=saved?.titulo||t.nomeInicial;field('start').value=saved?.inicio||new Date().toLocaleDateString('en-CA');field('end').value=saved?.fim||'';field('file-info').textContent=saved?.nomeFicheiro||t.semPDF;}fill();
async function validate(file){if(file.size>30*1024*1024)throw Error(t.tamanhoErro);const bytes=new Uint8Array(await file.arrayBuffer());if(!new TextDecoder().decode(bytes.slice(0,1024)).includes('%PDF-'))throw Error(t.pdfErro);const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';const task=pdfjs.getDocument({data:bytes});task.onPassword=()=>{task.destroy();};let pdf;try{pdf=await task.promise;if(pdf.numPages>40)throw Error(t.paginasErro);return pdf.numPages;}finally{if(pdf)await pdf.destroy();}}
let validating=false;
field('pdf').onchange=async()=>{const file=field('pdf').files[0];if(!file)return;validating=true;status(t.validar);try{const pages=await validate(file);candidate={blob:file,nomeFicheiro:file.name};field('file-info').textContent=`${file.name} · ${pages} ${t.paginas}`;status(t.pronto);}catch(err){candidate=saved;field('pdf').value='';status(err.message||t.pdfErro);}finally{validating=false;}};
function value(){if(validating)throw Error(t.validar);if(!candidate?.blob)throw Error(t.escolher);if(!field('title').value.trim())throw Error(t.nomeErro);if(!field('start').value||!field('end').value||field('end').value<field('start').value)throw Error(t.datasErro);return {...candidate,titulo:field('title').value.trim(),inicio:field('start').value,fim:field('end').value,exemplo:false,caminho:'local.pdf'};}
root.querySelector('form').onsubmit=async event=>{event.preventDefault();try{const next=value();await saveFlyer(next);saved=candidate=next;status(t.sucesso);}catch(err){status(err.message||t.guardarErro);}};
field('preview').onclick=async()=>{try{await openViewer(value(),cfg.textos,()=>'<span aria-hidden="true">×</span>');}catch(err){status(err.message);}};
field('reset').onclick=async()=>{try{await resetFlyer();saved=candidate=null;field('pdf').value='';fill();status(t.reposto);}catch{status(t.guardarErro);}};
}catch(err){root.textContent='Não foi possível abrir o painel. Verifique os dados e o armazenamento do navegador.';root.removeAttribute('aria-busy');}
