import {esc as e,safeUrl,loadScript} from './utils.js';

export async function openViewer(flyer,t,icon){
 if(document.querySelector('.viewer[open]'))return;const opener=document.activeElement;const dialog=document.createElement('dialog');dialog.className='viewer';dialog.setAttribute('aria-labelledby','viewer-title');dialog.innerHTML=`<header class="viewer-head"><div><h2 id="viewer-title">${e(flyer.titulo)}</h2><small>${e(flyer.exemplo?t.ui.demo:`${t.ui.validade} ${flyer.inicio} ${t.ui.ate} ${flyer.fim}`)}</small></div><div class="viewer-tools"><button class="icon-btn" data-action="out" aria-label="${e(t.ui.zoomOut)}">−</button><button class="icon-btn" data-action="in" aria-label="${e(t.ui.zoomIn)}">+</button><button class="btn outline" data-action="full">${e(t.ui.full)}</button><a class="btn outline" href="${e(safeUrl(flyer.caminho))}" download>${e(t.ui.download)}</a><button class="icon-btn" data-action="close" aria-label="${e(t.ui.fechar)}">${icon('close')}</button></div></header><div class="viewer-stage"><div class="book-scale"><div id="book"></div></div><p class="loading" role="status">${e(t.ui.carregar)}</p></div><footer class="viewer-bottom"><div class="page-controls"><button class="icon-btn" data-action="prev" aria-label="${e(t.ui.anterior)}" disabled>‹</button><span id="page-counter" aria-live="polite"></span><button class="icon-btn" data-action="next" aria-label="${e(t.ui.seguinte)}" disabled>›</button></div><span>${e(t.ui.pdfAjuda)}</span><a class="text-link" style="margin:0" href="${e(safeUrl(flyer.caminho))}" target="_blank" rel="noopener">${e(t.ui.pdfAcessivel)}</a></footer>`;document.body.append(dialog);dialog.showModal();document.body.style.overflow='hidden';let flip,pdf,loadingTask,zoom=1,cancelled=false;const stage=dialog.querySelector('.viewer-stage');const scale=dialog.querySelector('.book-scale');const action=name=>dialog.querySelector(`[data-action="${name}"]`);const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
 function clean(){cancelled=true;flip?.destroy();if(pdf)pdf.destroy();else loadingTask?.destroy();dialog.remove();document.body.style.overflow='';opener?.focus();}
 dialog.addEventListener('close',clean,{once:true});action('close').onclick=()=>dialog.close();
 action('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(dialog.requestFullscreen)await dialog.requestFullscreen();else throw Error();}catch{dialog.querySelector('#page-counter').textContent=t.ui.fullErro;}};
 function changeZoom(delta){zoom=Math.min(2,Math.max(1,zoom+delta));scale.style.zoom=zoom;action('out').disabled=zoom<=1;action('in').disabled=zoom>=2;}
 action('in').onclick=()=>changeZoom(.25);action('out').onclick=()=>changeZoom(-.25);changeZoom(0);
 function navigate(next){if(!flip)return;if(reduced){next?flip.turnToNextPage():flip.turnToPrevPage();}else{next?flip.flipNext():flip.flipPrev();}}
 action('next').onclick=()=>navigate(true);action('prev').onclick=()=>navigate(false);dialog.addEventListener('keydown',ev=>{if(ev.key==='ArrowRight'||ev.key==='ArrowLeft'){ev.preventDefault();navigate(ev.key==='ArrowRight');}});
 try{
 const [pdfjs]=await Promise.all([import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs'),window.St?Promise.resolve():loadScript('https://cdn.jsdelivr.net/npm/page-flip@2.0.7/dist/js/page-flip.browser.js')]);if(cancelled)return;
 pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';loadingTask=pdfjs.getDocument(safeUrl(flyer.caminho));pdf=await loadingTask.promise;if(cancelled){pdf.destroy();return;}
 const book=dialog.querySelector('#book');let ratio=1.414;
 for(let n=1;n<=pdf.numPages;n++){if(cancelled)return;const page=await pdf.getPage(n);const initial=page.getViewport({scale:1});ratio=initial.height/initial.width;const viewport=page.getViewport({scale:Math.min(1.7,1100/initial.width)});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;if(cancelled)return;const wrapper=document.createElement('div');wrapper.className='pdf-page';wrapper.setAttribute('role','img');wrapper.setAttribute('aria-label',`${t.ui.pagina} ${n}`);wrapper.append(canvas);book.append(wrapper);page.cleanup();dialog.querySelector('.loading').textContent=`${t.ui.carregar} ${n}/${pdf.numPages}`;}
 dialog.querySelector('.loading').remove();const pageHeight=Math.max(180,stage.clientHeight-40);const pageWidth=Math.min(430,pageHeight/ratio);flip=new window.St.PageFlip(book,{width:pageWidth,height:pageWidth*ratio,size:'stretch',minWidth:240,maxWidth:480,minHeight:240*ratio,maxHeight:680,showCover:false,usePortrait:true,autoSize:true,flippingTime:reduced?1:650,drawShadow:!reduced,maxShadowOpacity:.2,mobileScrollSupport:true,swipeDistance:25});
 const update=()=>{const current=flip.getCurrentPageIndex();const landscape=flip.getOrientation()==='landscape';const end=Math.min(pdf.numPages,current+(landscape?2:1));dialog.querySelector('#page-counter').textContent=`${t.ui.pagina} ${current+1}${end>current+1?'–'+end:''} ${t.ui.de} ${pdf.numPages}`;action('prev').disabled=current===0;action('next').disabled=end>=pdf.numPages;};flip.on('flip',update);flip.on('changeOrientation',update);flip.loadFromHTML(book.querySelectorAll('.pdf-page'));update();
 }catch(error){if(cancelled)return;stage.innerHTML=`<p class="viewer-error" role="alert">${e(t.ui.pdfErro)}</p>`;}
}
