import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=fs.readFileSync('js/nearest.js','utf8').replace(/import \{esc as e\} from ['"]\.\/utils\.js(?:\?[^'"]*)?['"];?/, '');
const {distanceKm,searchUrl,suggestionsFrom,placesFrom,matchingSuggestions,matchingPlaces,rankPlaces,dedupePlaces,expandStreet,postalCodeFrom,houseNumberFrom,normalizeQuery,explicitPlaceFrom}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const config=JSON.parse(fs.readFileSync('data/config.json')).geocodificacao;
const stores=JSON.parse(fs.readFileSync('data/lojas.json'));
assert.equal(distanceKm({lat:0,lng:0},{lat:0,lng:0}),0);
assert.ok(Math.abs(distanceKm({lat:0,lng:0},{lat:0,lng:1})-111.195)<.01);
assert.equal(distanceKm(null,{lat:41,lng:-8}),Infinity);
assert.ok(Number.isFinite(distanceKm({lat:0,lng:0},{lat:0,lng:180})));
for(const origin of stores){const ordered=[...stores].sort((a,b)=>distanceKm(origin.coordenadas,a.coordenadas)-distanceKm(origin.coordenadas,b.coordenadas));assert.equal(ordered[0].id,origin.id);}
console.log('Distâncias e ordenação das nove lojas: PASS');
assert.equal(normalizeQuery('São João / Sobretâmega'),'sao joao sobretamega');
assert.equal(normalizeQuery(null),'');
assert.equal(expandStreet('R. do Calvário'),'Rua do Calvário');
assert.equal(expandStreet('Av. Dr. Sá Carneiro n.º 116, 4630286'),'Avenida Doutor Sá Carneiro 116, 4630-286');
assert.equal(postalCodeFrom('4000 443 Porto'),'4000-443');
assert.equal(houseNumberFrom('Rua 25 de Abril'),'');
assert.equal(houseNumberFrom('Rua 25 de Abril, 12, Penafiel'),'12');
assert.equal(houseNumberFrom('Rua de Santa Catarina 312, Porto'),'312');
assert.equal(houseNumberFrom('Avenida da Liberdade 120A, Porto'),'120A');
const street=searchUrl(config,'Rua da Igreja');
assert.ok(street.pathname.endsWith('/suggest'));
assert.equal(street.searchParams.get('countryCode'),'PRT');
assert.equal(street.searchParams.get('location'),'-8.2,41.18');
assert.equal(street.searchParams.get('maxSuggestions'),'12');
assert.equal(street.searchParams.has('searchExtent'),false);
const explicit=searchUrl(config,'Rua de Santa Catarina 312, Porto');
assert.equal(explicit.searchParams.has('location'),false);
assert.equal(searchUrl(config,'Rua da Igreja Lisboa').searchParams.has('location'),true); // No hard bounds anywhere.
assert.equal(searchUrl(config,'Rua da Igreja, Lisboa').searchParams.has('location'),false);
assert.equal(searchUrl(config,'4630-286').searchParams.has('location'),false);
const resolve=searchUrl(config,'Rua da Igreja','resolve','a+b/key');
assert.ok(resolve.pathname.endsWith('/findAddressCandidates'));
assert.equal(resolve.searchParams.get('magicKey'),'a+b/key');
assert.equal(resolve.searchParams.get('forStorage'),'false');
assert.equal(resolve.searchParams.get('sourceCountry'),'PRT');
assert.equal(resolve.searchParams.get('matchOutOfRange'),'false');
console.log('Esri: sugestões, seleção por magicKey, Portugal, preferência automática sem limites e resultados temporários: PASS');
const suggestions=suggestionsFrom({suggestions:[{text:'Rua da Igreja, 4630, Marco, Marco de Canaveses, Porto, PRT',magicKey:'one',isCollection:false},{text:'Rua da Igreja, 4630, Marco, Marco de Canaveses, Porto, PRT',magicKey:'duplicate'},{text:'Rua de Santa Catarina 312, 4000-443, Porto, PRT',magicKey:'porto'},{text:'Rua Santa Catarina 312, 4620, Meinedo, Lousada, Porto, PRT',magicKey:'lousada'},{text:'Rua da Igreja, Portugal',magicKey:'collection',isCollection:true},{text:'Invalid'}]});
assert.equal(suggestions.length,4);
assert.equal(suggestions[0].title,'Rua da Igreja');
assert.ok(suggestions[0].description.includes('Marco de Canaveses'));
assert.equal(suggestions[0].label.endsWith('PRT'),false);
assert.equal(suggestions[3].collection,true);
assert.equal(matchingSuggestions(suggestions,'Rua de Santa Catarina 312, Porto',config).length,1);
assert.equal(matchingSuggestions(suggestions,'Rua da Igreja',config).length,4);
assert.equal(explicitPlaceFrom('Rua de Santa Catarina 312, Porto',config),'Porto');
assert.equal(explicitPlaceFrom('Rua da Igreja, Marco de Canaveses',config),'Marco de Canaveses');
assert.equal(explicitPlaceFrom('Rua da Igreja, Lisboa',config),'Lisboa');
assert.equal(explicitPlaceFrom('4630-286, Marco, Marco de Canaveses, Porto',config),'Marco');
assert.equal(explicitPlaceFrom('Rua de Santa Catarina 312, 4000-443, Porto',config),'Porto');
const candidate=(location={x:-8.606,y:41.149},attrs={})=>({address:'Rua de Santa Catarina 312, 4000-443, Porto',score:100,location,attributes:{Country:'PRT',Addr_type:'StreetAddress',City:'Porto',Subregion:'Porto',Postal:'4000-443',AddNum:'312',LongLabel:'Rua de Santa Catarina 312, 4000-443, Porto, PRT',...attrs}});
const parsed=placesFrom({candidates:[candidate(),candidate(),candidate({x:null,y:41}),candidate({x:-8,y:100}),candidate({x:-8,y:41},{Country:'ESP'}),{...candidate(),score:30}]});
assert.equal(parsed.length,1);
assert.equal(parsed[0].type,'interpolated');
assert.equal(parsed[0].housenumber,'312');
assert.equal(parsed[0].postcode,'4000-443');
assert.equal(placesFrom({candidates:[candidate(undefined,{Addr_type:'PointAddress'})]})[0].type,'house');
assert.equal(placesFrom({candidates:[candidate(undefined,{Addr_type:'PostalExt',AddNum:''})]})[0].type,'postcode');
assert.equal(matchingPlaces(parsed,'4000443').length,1);
assert.equal(matchingPlaces(parsed,'4000-444').length,0);
assert.equal(matchingPlaces(parsed,'Rua de Santa Catarina 314, Porto').length,0);
const wrongMunicipality={...parsed[0],city:'Meinedo',county:'Lousada',region:'Porto'};
assert.equal(matchingPlaces([wrongMunicipality,...parsed],'Rua de Santa Catarina 312, Porto',config).length,1);
assert.equal(dedupePlaces([...parsed,{...parsed[0],lat:41.14901},{...parsed[0],lat:41.4}]).length,2);
assert.deepEqual(placesFrom(null),[]);
assert.deepEqual(placesFrom({candidates:'broken'}),[]);
assert.deepEqual(suggestionsFrom({suggestions:'broken'}),[]);
assert.equal(rankPlaces([{...parsed[0],label:'Rua do Comércio'},...parsed],'Rua de Santa Catarina 312, Porto')[0].title,'Rua de Santa Catarina 312');
console.log('Sugestões claras, concelho explícito, portas/códigos exatos, precisão, deduplicação e rejeição de coordenadas/respostas inválidas: PASS');
